---
- name: Join Kubernetes Cluster
  become: yes
  command: "kubeadm join --discovery-token-unsafe-skip-ca-verification --token=2f1a31.00f66dec74fd53f3 --skip-preflight-checks=true 172.42.42.11:6443"
